repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: redis
    namespace: redis
    chart: bitnami/redis
    values:
      - replicaCount: 1
      - architecture: standalone
      - master:
          persistence:
            enabled: false
      - auth:
          enabled: false
          password: password
      - persistence:
          enabled: false