apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: vault-external-secret
    creationPolicy: Owner
  data:
    - secretKey: my-username
      remoteRef:
        key: secret/devwebapp/config
        property: username
    - secretKey: my-password
      remoteRef:
        key: secret/devwebapp/config
        property: password