apiVersion: v1
kind: Pod
metadata:
  name: longhorn-test
spec:
  containers:
    - name: test-container
      image: busybox
      command: ["/bin/sh", "-c", "sleep 3600"]
      volumeMounts:
        - mountPath: "/data"
          name: longhorn-vol
  volumes:
    - name: longhorn-vol
      persistentVolumeClaim:
        claimName: longhorn-pvc