defaultSettings:
  replicaCount: 3
  storageOverProvisioningPercentage: 100
  storageMinimalAvailablePercentage: 15
  nodeDownPodDeletionPolicy: "delete-both-statefulset-and-deployment-pod"
  replicaAutoBalance: "best-effort"
  dataLocality: "best-effort"
  rebalanceDisksWhenLowSpace: true

longhornManager:
  nodeSelector:
    storage: "longhorn"

longhornUI:
  nodeSelector:
    storage: "longhorn"

longhornDriver: {}
