---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: alphabet-certs-ecdsa
#  namespace: go-app
spec:
  secretName: alphabet-certs-ecdsa
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
    size: 256
  dnsNames:
    - alfa.beta-82.win
    - beta.beta-82.win
    - delta.beta-82.win
    - fox.beta-82.win