---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-certs-ecdsa
#  namespace: go-app
spec:
  secretName: grafana-certs-ecdsa
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
    size: 256
  dnsNames:
    - grafana.beta-82.win