---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: loki-certs-ecdsa
spec:
  secretName: loki-certs-ecdsa
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
    size: 256
  dnsNames:
    - loki.beta-82.win