apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-proxy-nginx-conf
  namespace: default
data:
  default.conf: |  # Измените имя файла на default.conf
    server {
      listen 8080;
      location / {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;    
        proxy_pass http://grafana-service.my-grafana.svc.cluster.local:3000;
      }
    }
