apiVersion: v1
kind: Service
metadata:
  name: grafana-proxy
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: grafana-proxy

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-proxy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-proxy
  template:
    metadata:
      labels:
        app: grafana-proxy
    spec:
      containers:
      - name: nginx
        image: nginx
        resources: {}
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        ports:
        - containerPort: 8080
      volumes:
      - name: nginx-conf
        configMap:
          name: grafana-proxy-nginx-conf
