apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-proxy-nginx-conf
  namespace: default
data:
  default.conf: |  # Измените имя файла на default.conf
    server {
      listen 8081;
      location / {
        proxy_pass http://vault.vault.svc.cluster.local:8200;
      }
    }
