apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secrets
  namespace: vault
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend # name  SecretStore
    kind: SecretStore
  target:
    name: vault-secrets2 # name create secret kubernetes
  data:
    - secretKey: user # ключ секрета
      remoteRef:
        key: dev/app # путь до секрета в vault
        property: user # ключ секрета в vault
    - secretKey: password
      remoteRef:
        key: dev/app
        property: password
    - secretKey: alfa
      remoteRef:
        key: dev/app
        property: alfa
#    - secretKey: value1 # <<< testing vault policy
#      remoteRef:
#        key: prod
#        property: value