---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-example
  namespace: go-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-app-example
  template:
    metadata:
      labels:
        app: go-app-example
    spec:
      containers:
      - image: denisitpro/go-example:latest
        name: go-app
        ports:
        - containerPort: 8082
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: 8082
          periodSeconds: 10
          successThreshold: 2
          timeoutSeconds: 3
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8082
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
          initialDelaySeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 300m
            memory: 512Mi