---
apiVersion: v1
kind: Service
metadata:
  name: go-app
spec:
#  ipFamilyPolicy: PreferDualStack
#  ipFamilyPolicy: SingleStack
#  ipFamilies:
#  - IPv6
  ports:
  - port: 8082
    targetPort: 8082
  selector:
    app: go-app-label
  type: ClusterIP