apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: go-app
spec:
  serviceName: "go-app"
  replicas: 2
  selector:
    matchLabels:
      app: go-app-label
  template:
    metadata:
      labels:
        app: go-app-label
    spec:
      containers:
      - name: go-app
        image: denisitpro/go-example:latest
        env:
          - name: AI_NAME
            value: "Ivan"
        ports:
        - containerPort: 8082
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 300m
            memory: 512Mi
        volumeMounts:
        - name: go-app-storage
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: go-app-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
      storageClassName: local-path