apiVersion: v1
kind: Service
metadata:
  name: go-app-service-lb
  annotations:
    load-balancer.hetzner.cloud/location: fsn1
    load-balancer.hetzner.cloud/name: lb1-go-app
    load-balancer.hetzner.cloud/disable-private-ingress: "true" #https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/main/docs/load_balancers.md
spec:
  selector:
    app: go-app-label
  ports:
    - port: 80
      targetPort: 8082
  type: LoadBalancer