apiVersion: v1
kind: Service
metadata:
  name: example-service-lb
  annotations:
    load-balancer.hetzner.cloud/location: fsn1
    load-balancer.hetzner.cloud/name: lb1
    oad-balancer.hetzner.cloud/disable-private-ingress: "true"
spec:
  selector:
    app: go-app-label
  ports:
    - port: 80
      targetPort: 8082
  type: LoadBalancer