apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: go-app
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200" # адрес нашего vault. Складывается из имени сервиса и пространства имен.
      path: "argocd" # kv store name
      version: "v2" # KV version
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "argocd-role" # vault role
          serviceAccountRef:
            name: "sa-vault-go-app" # service account name
