apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secrets-hcp-vault
  namespace: go-app
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend # name  SecretStore
    kind: SecretStore
  target:
    name: hcp-vault-secrets # name create secret kubernetes
  data:
    - secretKey: target1 # k8s key name
      remoteRef:
        key: argo-kv/dev/mind #path secret  vault
        property: target1 # key secret vault
    - secretKey: target2
      remoteRef:
        key: argo-kv/dev/mind
        property: target2

