apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-app-argo-direct2
spec:
  project: default
  source:
    path: go-app-example
    repoURL: https://github.com/denisitpro/k8s-edu
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: go-app
  syncPolicy:
    automated: {}

