apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-app-argo-helm
  namespace: argocd
  annotations:
    argocd-imageUpdaters: '[{"kind": "ImageTag", "registry": "docker.io", "image": "denisitpro/go-example", "tag": "latest"}]'
spec:
  project: default
  source:
    chart: go-app
    repoURL: https://denisitpro.github.io/helm-edu/
    targetRevision: 0.1.4
    helm:
      releaseName: go-app
      valueFiles:
        - values.yaml
      valuesObject: # option 1 overwrite
        aiName: "Erika"
#        secrets:
#          aiTarget:
#            secretName: hcp-vault-secrets
#            secretKey: target2
#      values: |  # option 2 overwrite
#        aiName: "Bob"
#        secrets:
#          aiTarget:
#            secretName: hcp-vault-secrets
#            secretKey: target2
  destination:
    server: "https://kubernetes.default.svc"
    namespace: go-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
#  syncPolicy:
#    automated: {}
## enabled sync policy docker tag
#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
#      autoSyncImageTagger:
#        containerImages:
#          - image: denisitpro/go-example
#            tag: latest