apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-app-argo-helm
  namespace: argocd
spec:
  project: default
  source:
    chart: go-app
    repoURL: https://denisitpro.github.io/helm-edu/
    targetRevision: 0.1.2
    helm:
      releaseName: go-app
      valueFiles:
        - values.yaml
      valuesObject:
        aiName: "Bob"
#        aiTarget:
#          secretKeyRef:
#            name: ai-secret
#            key: aiTarget
  destination:
    server: "https://kubernetes.default.svc"
    namespace: go-app
  syncPolicy:
    automated: {}