apiVersion: v1
kind: Secret
metadata:
  name: cf-api-secret
type: Opaque
data:
  beta_82_win: base64code-token
---
apiVersion: crds.kubeflare.io/v1alpha1
kind: APIToken
metadata:
  name: beta82-token
spec:
  email: test@example.com
  name: my-api-token
  valueFrom:
    secretKeyRef:
      name: cf-api-secret
      key: beta_82_win
