apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-go-app
  namespace: go-app
  annotations:
    spec.ingressClassName: "traefik"
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  tls:
  - hosts:
    - fox.beta-82.win
    secretName: fox-tls
  rules:
    - host: fox.beta-82.win
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: go-app
                port:
                  number: 80
            path: /
