apiVersion: v1
kind: Pod
metadata:
  name: kaniko-build
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args:
      - "--context=dir:///workspace"
      - "--dockerfile=/workspace/Dockerfile"
      - "--destination=denisitpro/go-example:kaniko-go3"
    volumeMounts:
      - name: kaniko-local-pv-mount
        mountPath: /workspace
      - name: kaniko-secret
        mountPath: /kaniko/.docker
      - name: dockerfile-cm
        mountPath: /workspace/Dockerfile
        subPath: Dockerfile
  restartPolicy: Never
  volumes:
    - name: kaniko-local-pv-mount
      persistentVolumeClaim:
        claimName: kaniko-local-pvc
    - name: kaniko-secret
      secret:
        secretName: kaniko-secret
    - name: dockerfile-cm
      configMap:
        name: dockerfile-cm