---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: seaweedfs-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: seaweedfs-storage
  csi:
    driver: seaweedfs-csi-driver
    volumeHandle: seaweedfs-test-volume
  # Статическое связывание PV с PVC
  claimRef:
    namespace: default
    name: seaweedfs-pvc

# ---
# kind: StorageClass
# apiVersion: storage.k8s.io/v1
# metadata:
#   name: seaweedfs-special
# provisioner: seaweedfs-csi-driver
# parameters:
#   collection: mycollection
#   replication: "011"
#   diskType: "ssd"