---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seaweedfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: seaweedfs-csi
