---
# todo remove - need for test network policy
apiVersion: v1
kind: Pod
metadata:
  name: python-redis
  labels:
    app: python-redis
spec:
  containers:
    - name: python-container
      image: python:bullseye
      command: ["python3", "-m", "http.server", "8080"]