apiVersion: v1
kind: Pod
metadata:
  name: python-pod
  labels:
    app: python-pod
spec:
  containers:
    - name: python-container
      image: python:bullseye
      command: ["python3", "-m", "http.server", "8080"]